# Generated by Django 5.2.8 on 2026-06-07 09:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_vote_vote_has_target_alter_vote_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='valid_vote_value',
        ),
        migrations.RemoveConstraint(
            model_name='vote',
            name='vote_has_exactly_one_target',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(1500)]),
        ),
        migrations.AlterField(
            model_name='communityuser',
            name='display_name',
            field=models.CharField(default='ምእመን', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_notifications', to='community.communityuser'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.post'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.communityuser'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent'], name='community_c_post_id_f91575_idx'),
        ),
        migrations.AddIndex(
            model_name='communityuser',
            index=models.Index(fields=['created_at'], name='community_c_created_0d38b1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='community_n_recipie_751b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_deleted', '-created_at'], name='community_p_is_dele_7c4c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['post', 'user'], name='community_v_post_id_ff2564_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['comment', 'user'], name='community_v_comment_2358e6_idx'),
        ),
    ]
