# Generated by Django 5.2.8 on 2026-07-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_post_author_alter_vote_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='public_name',
            field=models.CharField(db_index=True, default='ምእመን', max_length=50),
        ),
    ]
